### ISSUE TITLE
Dealing with threads  and concurrency

### ISSUE THREAD

**Issue by adventureloop** [taps-api/drafts#160]
#155 #156 and #157 all stem for considerations in multithreaded environments. 

NEAT handled multithreading by not doing it.  Concurrency had to happen at the context level. I would quite like to take that easy way out and force each context onto its own thread and make the application deal with locking. The implementation draft is probably the correct place for such text. 

Are there arguments for other implementations that lean the other way?

**Comment by tfpauly** [comment]
From an implementation perspective, I do strongly believe that efficiency is served best by having a single threading context for a networking stack context. You may have multiple contexts per process if you need very different threading properties, but most connections should be sharing the same thread. This also, as you mention, simplifies locking quite a bit.

For our implementation, we use a Grand Central Dispatch (lib dispatch) abstraction of a queue of work instead of a pthread, so there are good asynchronous block execution semantics, although things are still on effectively one thread.

Not sure exactly how the text should be written here—I don't want to get too platform specific, but we should be able to distill the general approach.

**Comment by philsbln** [comment]
From our experience with adding concurrency to our socket intents prototype, introducing additional threading or new things that might block is extremely error-prone.

We should definitely consider some of the guarantees requested in #155 #156 and #157, but I don't want to suggest a specific threading model / automatic creation of threads.

If you already have a framework like GCD or libevent in place, it makes sense to integrate with those.
I guess we should start with some requirements / limitations we know of, start implementing (including language bindings for multiple languages) and incrementally add lessons learned that are not specific to just a single language.

**Comment by britram** [comment]
closing this as no further discussion after the constituent issues were closed.
