### ISSUE TITLE
Connection properties in "Setting and Querying of Connection Properties" are not well structured and underspecified

### ISSUE THREAD

**Issue by philsbln** [taps-api/drafts#190]
In Section 9 – "Setting and Querying of Connection Properties" – the properties of an established connection and path are heavily underspecified.

Should be fixed along with #153.

**Comment by theri** [comment]
I'm working on this issue within our pull request for #153, using the terminology we as simplified there.

For Section 9, I'm proposing the following:
* An application can query Connection Properties on a connection.
* Connection Properties include the status of the connection and whether it is possible to send and to receive data on it. (One of them might not be possible, e.g., in a unidirectional connection.)
* Additionally, Connection Properties include the Connection's Transport Properties. 
* Transport Properties include Selection Properties, so the application can know which Protocol Selection Properties had been specified, and which ones are actually supported by the protocol that has been chosen.
  * For Establishing connections (i.e., we are not done racing yet, the final protocols have not been selected yet), the application gets the Selection Properties that had been specified on the Preconnection earlier.
  * For Established, Closing, or Closed connections (i.e., the protocols have been selected), the application learns whether the Selection Properties are actually provided by the selected protocols. For example, if the application specified earlier, "Control Checksum Coverage: Prefer", now it will get "Control checksum coverage: True", indicating that on this connection it can indeed control the checksum coverage.
* Transport Properties also include Protocol Properties (Generic and Specific). These Protocol Properties can still be modified by the application. Basically, Protocol Properties are the only thing that the application can still set, everything else it can only query at this point.
* Finally, the application can query properties of the path. Not sure how well we have to specify them, probably this part will be implementation-specific just like, e.g., the Interface Instance or Type.

Does everyone agree, or is there anything to discuss here?
For me this is not a big change, it's just putting what was already there in terms of #153. The only thing I'm wondering if whether the Protocol Selection Properties of the finally chosen protocols are still "Selection Properties", as the selection is already done. That's why they were called "Transport Features" before, but now I want less terms and they're almost the same thing...

**Comment by gorryfair** [comment]
OK - so I commented on these things before - but in these things I think I agree. I'd personally prefer to keep the features as attributes implemented in the transport (etc) and the properties as the things requested. Indeed this begs the question about what to call the resulting transport when you selected properties and now get a transport. I think still calling them (for consistency) properties seems really good to me. :-).
