### ISSUE TITLE
API: Max message / transmission size

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#203]
I am still unsure whether max message size is constrained by the discovered path MTU, or is more like the maximum data gram  payload size that can be passed. 

To me: These could be quite different. After working on plpmtud, I now think we need both.

The words:
This property, if applicable, represents the maximum Message size that can be sent without incurring network-layer fragmentation and/or transport layer segmentation at the sender. 
Leaves me still uncertain because of the “and/or”
Another thing is the behaviour  of the value ...
*  in tcp and over http  the use for this is a connection property, effectively agreeing the size of pdu to be exchanged over the connection at setup. Apps have no need to know the underlying value of the MSS.
* Quite the converse for UDP/sctp/dcc where apps need to know and find out the max packet (data gram payload) size as they send during a flow. This changes with time and apps need to know this.

**Comment by mwelzl** [comment]
> I am still unsure whether max message size is constrained by the discovered path MTU, or is more like the maximum data gram payload size that can be passed.

I think it's the latter everywhere except in the part that you quote - the readable property "Maximum Message size before fragmentation or segmentation". There, it's about the Path MTU.

The value's behavior could be determined at run time, as it is queried for a connection. This is then for the implementation draft. The "and/or" translates into "with P(LP)MTUD / without P(LP)MTUD", I'd say.

What's missing or wrong here?

**Comment by gorryfair** [comment]
I don’t understand how that works. These are 2 different things

Gorry

**Comment by mwelzl** [comment]
It's a moot point to discuss: clearly, the text is too confusing as it is. We should clear it up.

**Comment by mwelzl** [comment]
I now tried to fix this in the text. After careful consideration, my fantastic update was to only change "and/or" into "or" in the text that we were discussing. That is, the description of the property "Maximum Message size before fragmentation or segmentation" now reads: "This property, if applicable, represents the maximum Message size that can be sent without incurring network-layer fragmentation and/or transport layer segmentation at the sender."  (check https://github.com/taps-api/drafts/blob/master/draft-ietf-taps-interface.md if you want to take a look - it seems that the scripts that create the nicely formatted page at https://taps-api.github.io/drafts/draft-ietf-taps-interface.html have stopped).

So let's see if this is clear: my understanding is that the three read-only properties "Maximum message size concurrent with Connection establishment", "Maximum Message size on send" and "Maximum Message size on receive" mean the maximum datagram payload size that can be passed. That's also what the text says.

Now, to have some control on fragmentation, one may also want to ask for (and maybe get: "N/A") the maximum message size that can be passed without incurring fragmentation in the sender or in the network. That is, the transport system would have to give back the PMTU minus header overhead to the application - it's the maximum payload that won't lead to fragmentation anywhere. This is the information provided by the property "Maximum Message size before fragmentation or segmentation".

While I'm not sure we need to use the words "segmentation" here, else I would think the description of this transport property already says that clearly enough?!  I mean, what's the application got to do with the PMTU itself, of course "message size" is about the message that the application is dealing with. I think that's implicitly clear because all is about specific "messages" here, which are passed from applications to the transport system and back.

**Comment by gorryfair** [comment]
I'm not quite sure where we have arrived, so let me try some points/questions:

• Maximum Message size before fragmentation or segmentation
- OK. I'd imagine this is the MPS specified  in DPLPMTUD. You could get a value for TCP, but I am not sure what the TCP PMTU or even the MSS means to an App using TCP or TLS.
- This changes when the PLPMTU/PMTU algorithm updates.
- This only has impact when "DF" is set for IPv4 and there is no endpoint frag.

• Maximum Message size on send
- OK. This is the largest size you can send:-), For Datagram transports is this the Min of (the largest size I can send, and the largest size an endpoint can reassemble)?
- It sounds like this is frozen on connect.

• Maximum Message size on receive
- Is this the largest size an endpoint can reassemble?
- It sounds like this is frozen on connect.

So.....
Is there a property that says the message is (non)fragmentable? (DF in IPv4 and no endpoint frag).
- clearly that only has an action if you do not use TCP, TLS, etc.

Do we assume the App does not do PLPMTU (in which case we need to be able to send probes>MPS and to set DF), and expect that to run beneath TAPS (where we may not need to worry)?

**Comment by mwelzl** [comment]
> On Sep 6, 2018, at 1:35 PM, Gorry Fairhurst <notifications@github.com> wrote:
> 
> I'm not quite sure where we have arrived, so let me try some points/questions:
> 
> • Maximum Message size before fragmentation or segmentation
> 
> OK. I'd imagine this is the MPS specified in DPLPMTUD. You could get a value for TCP, but I am not sure what the TCP PMTU or even the MSS means to an App using TCP or TLS.
> This changes when the PLPMTU/PMTU algorithm updates.
> This only has impact when "DF" is set for IPv4 and there is no endpoint frag.
Yes to all!

> • Maximum Message size on send
> 
> OK. This is the largest size you can send:-),
Yes

> For Datagram transports is this the Min of (the largest size I can send, and the largest size an endpoint can reassemble)?
It’s the largest size you can send, as exposed by the transport (if available). It would be reasonable to implement this as you say, but I don’t know of any implementation that can do that.
(the abstract APIs of the protocols we considered in RFC 8303 and RFC 8304 don’t expose such a thing, or we missed it, which would surprise me).

> It sounds like this is frozen on connect.
Yes

> • Maximum Message size on receive
> 
> Is this the largest size an endpoint can reassemble?
I guess so; in case of UDP, I would think it is GET_MMS_R from RFC 8304.

> It sounds like this is frozen on connect.
Yes


> So.....
> Is there a property that says the message is (non)fragmentable? (DF in IPv4 and no endpoint frag).
> 
No !!!
From minset, we must have that - either we had it and accidentally lost it in the updates, or we forgot to include it. Great catch!


> clearly that only has an action if you do not use TCP, TLS, etc.
> Do we assume the App does not do PLPMTU (in which case we need to be able to send probes>MPS and to set DF), and expect that to run beneath TAPS (where we may not need to worry)?
> 
I don’t think we should make this assumption, given that PLPMTU using UDP options isn’t available everywhere yet. This way, DPLPMTUD could be rolled out gradually underneath, providing an MPS value when it’s available, and when that is available, it’s reasonable for the application to assume that some form of PMTUD is happening and it doesn’t need to do this job.

Cheers,
Michael

**Comment by gorryfair** [comment]
OK so one thing is we spotted a need for something (a flag, I'll call flag1) to trigger DF, etc. I think we agree.

(1) When an endpoint sends a datagram and uses DPLPMTUD or PMTU for datagrams, it will by default send packets less than the MPS that set the DF flag in IPv4 and instruct the stack to not perform endpoint fragmentation of datagrams. A datagram app can explicitly clear that mode and permit fragmentation to take place. If an App can get an MPS from the OS, then it should use this.

(2) And this is how that (kindof) works:
* Some stacks do maintain a host cache and use something link PMTU or at least black hole detection to store a value per IP address(es). I suspect much of this machinery is broken in a world where ICMP messages are dropped and ECMP is common, but PMTUD basically works by clearing the cache periodically and waiting to see if it gets an ICMP message. If it exists this cache seems to be the basis for a "legacy" stack to give you a value for "Maximum Message size before fragmentation or segmentation". That's all OK.  If DPLPMTUD happens to be enabled lower in the stack (in SCTP, UDP-Options, etc) then this will all work as expected:-).

(4) However in theory an app could also perform DPLPMTUD :
* I'm not convinced datagram apps do perform DPLPMTUD at the app layer (but would love examples)  - you would then need at least to set the above flag1 to force DF and no endpoint fragmentation, but then also need to set another "flag2", to tell the stack that the host cache entry is not to be used for this specific datagram. This "flag2" is what lets the app send a probe packet larger than the cached (PL)PMTU, and starting with this is what could finally trigger an increase in the MPS by raising the (PL)PMTU (which would require yet another call to do update the cache).  I'm unsure of the current availability and degree of standardisation of these extra flags in current stacks, and how you would tell the stack that PMTUD shouldn't be done, because the app is doing PLPMTUD...
Someone who understands a range of OS'es may help me... ?

So...  My starting suggestion is for TAPS to document it as if PMTUD or PLPMTUD is done lower in the stack (i.e. (1) assuming (2) being done) and to stay quiet for the moment about (3).

What do you think?

Gorry

**Comment by mirjak** [comment]
If I'm following this correctly, I think the point is that if you use a real transport then it's a transport feature that is hidden from the app. If you use UDP (which is not a transport) you may have to implement it yourself. I think UDP is a special case here and as such this flag is a protocol/UDP-specific configuration.

**Comment by gorryfair** [comment]
That's very annoying: UDP **IS** a transport!

That aside, a UDP-App needs to decide what to do - at least for IPv4, there may be good reasons to not set DF and allow fragmentation.

If you say tunnels and user-land stacks can not be used over the top of TAPS then, maybe you can manage without the flags. That depends on what can be layered over "UDP".

Gorry

**Comment by mwelzl** [comment]
@mirjak SCTP can do this too: https://tools.ietf.org/html/rfc6458#page-68
I guess this can be generally helpful as part of Application-Layer Framing.

I conclude that we really want a "Don't Fragment" Message Property.

**Comment by mwelzl** [comment]
Thanks! I think that's the only thing. Gorry?

**Comment by mwelzl** [comment]
What? Decide that they *can't* do app-layer PMTUD? But I think we must make it possible for them to do it, and that's what the "don't fragment" + "max size before fragmentation" things are about.

**Comment by gorryfair** [comment]
We are not in synch. That happens. I'll try again:

(1) To utlise PMTUD (at the IP layer) or PLPMTUD (below the TAPS API), then you need to set DF and disable source fragmentation. I think this should be the default. Packets will fail when larger than the "max size before fragmentation" size, and therefore it is really helpful for the user of the TAPS service to know that. In some cases, the MPS can be too small for an app (even ridiculously small for IPv4), apps have a choice to clear the flag to potentialy trigger source/network fragmentation. #226  is about this.

(2) To *implement* PLPMTUD/DPLPMTUDin an app above TAPS will need more functions at the API (to over-ride the host cache, and  either reset the host-cache or disable network PMTUD). I was asking whether there is an important need to add this to our TAPS interface, and I suggest we could decide to be silent on this topic in this spec.

**Comment by mwelzl** [comment]
Thanks for explaining!

So it seems to me that this is still not resolved. I would like to make it possible for a system underneath the TAPS API to implement PMTUD (which it will signal by providing a value via "max size before fragmentation") AND for the application itself to implement PMTUD.

About 1: I agree, in principle - but there's one exception: I don't know how it would be handled in case of TCP. Here, you can't get any reasonable number back in "max size before fragmentation" and you should be allowed to send arbitrarily large messages if you want. So, JUST because of TCP, I would NOT make "set DF and disable source fragmentation" the default.

About 2: Here I don't understand why you need to over-ride or reset the host cache - because, which protocol are you talking about? For TCP, we shouldn't be doing this anyway. For UDP, right now, there isn't any functionality below, so why would it not work to implement PMTUD in the application based on what we have right now?

If your wish is to support UDP PMTUD underneath TAPS, I understand that, and I imagine that it complicates things a little, and I'd agree to be silent about this *for now*. We could get back to this discussion later.

Does that make sense?

**Comment by gorryfair** [comment]
I'm not explaining well:

I think we agree:  "max size before fragmentation" and teh flag allows a system underneath the TAPS API to implement PMTUD.

TCP needs to return the largest message it can support - presumably the socket buffer size? or perhaps infinite for a stream? I think TCP ignores the flag and interanlly always behaves as if the " "set DF and disable source fragmentation"" was true. It fragments at the transport, not network layer.

I'll explore (2) in some real OS code, but for me, that's a story for later, not now.

Gorry

**Comment by mwelzl** [comment]
Ok, I think we have converged. Thanks!
