### ISSUE TITLE
Clarify what a framer is and what it can do 

### ISSUE THREAD

**Issue by philsbln** [taps-api/drafts#271]
In the discussion of Issues #266 and #249 we encountered that the current document do not really describe what a framer is and can do.

Non-conclusive list of open questions:
- Do framers only determine frame boundaries (as Linux KCM) or do they parse whole message and return nice objects?
- Are framers stackable?
- What functionality/API can framers use 
- Do we want a bunch of standardised framers to implement (pseudo-)protocols like HTTP
- Can we switch framers (e.g.,  to implement STARTTLS)

**Comment by britram** [comment]
A first pass at these. I'm going to start with the last one, because IMO it's the only question driven by the demands of the protocols we implement in TAPS (which should be the source of requirements in an abstract API)

>    Can we switch framers (e.g., to implement STARTTLS)

This is the most important question in this pile IMO, since the answer determines the set of protocol stacks we can "assist" with framing. I think we want the ability to switch framing modes. The subquestion here seems to be how modeswitching works:

- does the framer switch its own mode, 
- or does it ask the TAPS system to switch to a different framer,
- or does it ask the application to switch to a different framer,
- or does the application have to notice it's in a different mode and switch to a different framer.

Implementation issues here seem mainly to be related to pushback and buffering.

>    Do framers only determine frame boundaries (as Linux KCM) or do they parse whole message and return nice objects?

This seems to me to be implementation-dependent -- it turns a bytestream into whatever message abstraction the API presents to its client. Different implementations are going to have different reasons to have the thing returned/consumed have a different shape.

>    Are framers stackable?

This seems to depend on the answer to the question above, which means it's implementation dependent.

>    What functionality/API can framers use

This... also seems implementation dependent -- restrictions on framers are up to the environment the implementation provides for framers. (ISTM that framers should almost-always look like functions, but whether those functions have a hook for, e.g., maintaining state is... implementation-depedent.)

>    Do we want a bunch of standardised framers to implement (pseudo-)protocols like HTTP

If the framers are implementation-dependent, then this seems like "no". We could suggest a set of framers that should be made available, and names for them, I suppose. But otherwise this seems like overspecification for an abstract interface.

Let me add another question to this list: do we need to somehow explicitly support the notion of hardware-accelerated framers?

**Comment by mwelzl** [comment]
As y'all know, I favor simplicity. I'm sceptical about layered framers etc. ***being an issue for the TAPS API design***  (I'm not at all sceptical about such things existing in code!).  My view is that framers should essentially be a hook to a function to frame or deframe, and yes you should be able to change it, at your own risk, anytime you want. Luckily, so far, that seems to match what we have in the text, except that we don't have text allowing to change framers on existing connections so far (I think it should be added).

So, from that perspective, I'm very happy with everything @britram says in his answer here: implement what you wish, but let's not concern the API with it.

Regarding @britram's question: how mode switching would work - here I'd be tempted to quickly shoot "the app can decide, whenever, just supply a new function and that's it", but the mention of pushback and buffering makes me wonder if I'm missing something. Maybe, just maybe, that simple approach isn't good enough. I'd suggest to choose this option for now until someone sees a case where this causes a real problem.

About hardware-accelerated framers, I guess @tfpauly

**Comment by csperkins** [comment]
I tend to agree with @britram and @mwelzl. My view of framers was as functions of the form:
``
fn deframer(newly_received_data, saved_context) -> (parsed_object, context_to_save)
``
I'd expect a particular implementation of TAPS to provide a standard set of these framers that are instantiated when the connection is setup for a known pseudo-transport, or you can pass a custom deframer for a new protocol.

Do we need to stack framers? I'm not sure. An implementation would likely be engineered to allow message parsing and de-framing code to be internally composed in some way, but conceptually it's not clear we need more than a single level in the API. Features like STARTTLS can be conceptually handled within an HTTP framer, for example.

**Comment by mwelzl** [comment]
Closing this because the useful remnant of this discussion is continued in #249.
