### ISSUE TITLE
"Connection Group" should be an Object

### ISSUE THREAD

**Issue by mwelzl** [taps-api/drafts#31]
... I think. Right now it's only written as a Transport System implementation concept, tied to multiplexing - but it does have a meaning for an application developer.

Proposed definition:

Connection Group

A Connection Group is a set of Connections which are entangled: they share the same properties, and changing properties for one of them influences the others. To influence how network capacity is divided, an application can assign priorities to individual Connections within a Connection Group.

**Comment by tfpauly** [comment]
I know we had discussed this at the meeting. I don't agree that the Connection Group is a fundamental object. It may be an "object" in the code-based API that can be introspected and used for relating connections, but the objects in the architecture are the fundamental things you operate on. You don't ever read or write, or start, a connection group (in my mind).

Connection Group is a Concept right now in the implementation section; I could also see it being an attribute in the Pre-Establishment, like a "Connection Group ID" to be a tag to tie connections together.

Also, with regards to priority, I think we can assign priorities to connections regardless of their being in a group. If I as an applications set certain priority values, like Priority 1 on Connections A and B, Priority 7 on Connection C, and Priority 20 on Connections D and E, I've expressed relative priority that can apply if they are grouped into a multiplexed transport, but also priority that will help in the IP-level interface queues on my device. Priority SHOULD NOT be expressed only in connection groups, since it is more broadly useful.

**Comment by mwelzl** [comment]
Sorry, maybe we didn't finish the discussion... or it's my memory...

So let's see. Your first two paragraphs, I agree with (indeed, you don't write to a connection group). About the last paragraph, I agree that priority should not *only* be expressed in connection groups - e.g. it can affect a DSCP setting. However, a connection group can allow you to precisely (when you're lucky and there is e.g. multiplexing available) assign a capacity share to connection within that group. Sure, some things are generally more important than others - but that's a different thing from requesting to divide the capacity, e.g. 5:1:1 between 3 connections.  I do think this is a valuable piece of functionality that we don't want to take away.

Now, if this warrants connection groups being a concept in the architecture or not, I'm not sure... visible and controllable in the API, for sure.

**Comment by tfpauly** [comment]
Yes, good point for the sharing (5:1:1). For this, it would make sense to have an API to give the balance if applicable. I do see those as APIs to tweak behavior either before establishment, or during the connection, to say "when multiplexing, divide the work like this". My concern with adding that into the fundamental architecture concepts is that the method for these options is not very generic (doesn't apply to single stream protocols) and may not have the same meaning across different multi-streamed protocols. QUIC may have different multiplexing knobs from HTTP/2, from SCTP, etc.

**Comment by mwelzl** [comment]
Got it - fine by me to not put it in the architecture, then. These API tweaks, I already included in the API doc.
