### ISSUE TITLE
Design API for UDP lite (and similar protocols if there are any)

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#36]
§5.2.1 defines "Control checksum coverage..." (from minset) as a transport selection property, but there is no support for this in §7 Sending. Need to figure out how to reconcile this.

**Comment by britram** [comment]
It seems to me that this is a different kind of unreliability. Lifetime lets some Content be marked as "I don't care if it gets there because I have my own application-layer method for dealing with it if it doesn't". This per-Send parameter would say, in essence, "this part of the Content can even get scrambled because I have my own application-layer method for dealing with *that*"

UDP-Lite is a weird animal, though, and I'm not sure how much complexity we need to add to the API to accomodate it.

**Comment by mwelzl** [comment]
This checksum stuff is in §7.1.6, by the ugly name of "Checksum" because I thought that we can come up with something better than "integrity", and in the meantime, let's just call it checksum.

I agree that this relates to (Un)reliability, but I believe adding this to "Lifetime" just ends up making things more complex than if we have it as a separate send property. As for UDP-Lite being weird and this being worth it or not, I don't think this is much complexity to add, and anyway just an optional thing to configure for folks who want. UDP-Lite may be "weird" because people don't use it, they don't even try to, because the interface doesn't offer it, and because no app even tries to use it, it may seem like a useless protocol .... hmmm, does this sound familiar?  :-)   yes it's the same circular dependency problem that's at the roots of the whole TAPS stuff - this problem is all over the place. So if our goal is to offer deployability of transport features that people may not get to use today, we have to start by adding them to the API.

**Comment by britram** [comment]
yeah, trying to make lifetime cover this would be wrong.

My "UDP Lite is a weird animal" is less of a comment on the service it provides (marginal improvement of loss rates in those environments where L2 doesn't have a checksum and/or RTX facility and L1 is noisy... itself a rare circumstance, but I suppose it's useful where that circumstance does hold) and more on *how* it provides it (i.e., it's a hack). 

The generic send parameter here would be "corruption tolerance" over a *portion* of a Content, with the added caveat that UDP Lite that portion must be at the *end* of the content. A Send Parameter that says "it's okay to break the last N bytes" of the content would map to the UDP Lite implementation nicely, but it's not clear to me that it would *ever* be implemented by anything other than UDP Lite.

**Comment by britram** [comment]
What's in §7.1.6 is good enough for now; we can revisit in the -01 rev.

**Comment by mwelzl** [comment]
Closed or not, I do want to answer because this is one of *my* favorite topics   :-)   so I think the checksum length field is hacky, but it can work - there are cases of audio codecs that align with this kind of setup. Anyway, disabling the checksum altogether can be more useful. About this being a rare occurrence, I have a fun fact to share: Mattia Rossi, whom I think you know too?  measured this for WiFi in his master thesis with me - he hacked the driver to disable the link layer CRC, and found a whopping 2 or 3 packets with errors in a couple of thousands (something in that order). Yet, there are tests that others made, with much happier results - I think the bottom line is, it heavily depends on the link layer.

Was this relevant? No sir... but I couldn't stop myself  :-)

**Comment by britram** [comment]
> Was this relevant? No sir... but I couldn't stop myself :-)

I learned something, so.

> I think the bottom line is, it heavily depends on the link layer.

Agreed, when you need it, you really do need it. 

"Disable completely or not" is a good first pass solution.

For maximum generality, you'd be able to mark arbitrary byte ranges for checksum coverage (or, looking further ahead, cryptographic integrity / confidentiality coverage). But UDP-lite can't implement that, and it may be impossible to implement the general case efficiently.

**Comment by mwelzl** [comment]
Hm, I'm not sure I like the "either clean because we remove the hacky stuff" or "clean because we made it more general" approach. Case 1 may make the API "lame" - I see it as a problem if we sell this as a general thing atop Internet protocols, but if you want to do cool stuff, you really need to use the protocols directly. Case 2 doesn't map onto any existing protocol for now, which may not be a problem, but I can't see this worth the added complexity (because, indeed, defining arbitrary byte ranges can become a quite complex thing to add to the API).  So, I'd like to keep it as it is, with the checksum length adjustable.

**Comment by csperkins** [comment]
Being able to support https://tools.ietf.org/html/rfc4867#section-3.6.1 seems a useful goal for a UDP-lite API.
