### ISSUE TITLE
Make some choices about §5.2.1 Transport Selection Parameters

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#37]
Do all of the transport selection parameters in §5.2.1 need to be listed in the proposed standard interface? Discuss.

**Comment by mwelzl** [comment]
I'm not sure about the following ones:
- Suggest a timeout to the peer
- Notification of special errors (excessive retransmissions, ICMP error message arrival)

I wonder if "suggest a timeout to the peer" is something that should be dealt with inside a transport system (if at all), not by the application on top. From RFC 5482: "Decreasing the user timeouts allows busy servers to explicitly notify their clients that they will maintain the connection state only for a short time without connectivity."

Since we maintain a higher level "connection" concept, a transport system could just take care of re-connecting in case it would get such a notification, and not bother the application with it.

Does that sound reasonable?


The second, well ... is anybody *really* going to pick a protocol because it gives you richer error messages than another one?

**Comment by mwelzl** [comment]
I'm answering myself (rather than editing, because maybe these thoughts are helpful to others too): about error messages, sure they are helpful, at least for applications doing PMTUD. If we don't want this, we have to abstract it away and provide the right hooks for people doing PMTUD - I think this is a possible discussion for the next draft version.

About the timeout thing, because this comes from minset, I thought, if this is not needed then there must be something wrong in minset... so I checked: both this, and the other timeout configuration parameter are functional because "this is closely related to potentially assumed reliable data delivery."  I think this is right - for applications for which the notion of a "connection" is the same as the transport protocol's notion of a connection. But we provide something higher-level here... so we can offer such timeout primitives to apps, at least a local one - yet we may not care about offering these transport timeout primitives to applications at all, and deal with them inside the Transport System.

My conclusion is: keeping a local timeout decision as a "protocol property" (which applies after selection, and may or may not be handed down 1:1 by the transport system!) makes sense, as we have it, in section 5.2.2 - it's just about "our" connections, not about the actual transport protocol's connections.

Because we deal with transport connections below the API, we can then delete the protocol properties "Set timeout to suggest to the peer", "Set retransmissions before 'Excessive Retransmissions' " (which isn't semantically hugely different from a timeout), and the protocol selection property "Suggest a timeout to the peer".

Thoughts?

**Comment by theri** [comment]
> Since we maintain a higher level "connection" concept, a transport system could just take care of re-connecting in case it would get such a notification, and not bother the application with it.

Sounds alright to me, as long as the application is at least notified in this case. I initially read "not bother the application with it" to mean that the application wouldn't be notified, but perhaps I misunderstood.

I think the point from minset is right: Timeouts are closely related to assumed reliability. Not just about whether the data will eventually reach the application at the remote endpoint, but there's also an assumption about the stability of the connection. So we have to think about our definition of "reliability" here.
In the current API we define "Reliable Data Transfer" to include "being notified when a Connection is closed or aborted". Does this mean "notify when the TCP connection breaks, but reestablish it"? Always, or just for some connections or in some applications where it makes sense?
I think the Intent "Disruption Resilience" relates to this - does terminating the, e.g., TCP connection result in application failure or not?

Now, about keeping the "Suggest timeout to the peer" option in this API: Intuitively I'd be okay with just letting the application set a local timeout and then maybe having a failover if the application is terminated from the other end, so I'd be fine with the changes that Michael proposes.

**Comment by abrunstrom** [comment]
> Since we maintain a higher level "connection" concept, a transport system could just take care of 
> re-connecting in case it would get such a notification, and not bother the application with it.

In the general case you can not just reconnect, you have no corresponding state on the other end at the taps-level and you do not know what the application is doing? I have no idea what a local timeout on the taps connection level really means here? I could imagine setting timers for how long you want to wait for a given event or something like that, but for the timers in question here I think they need to map to the protocol timers or I am not sure what they mean. How would this local timer be defined?

**Comment by mwelzl** [comment]
Hmmm. Maybe I'm inventing too much stuff here. So yes, just re-connecting can work or not...  this depends on the application on the other side. The timers may or may not have to related to protocol timers - this depends on whether we want to support a "retransmission count" timeout. Anyway, I suggest to leave this as it is for now but maybe discuss in London if there can be a cleaner, more uniform way to handle these things, for v1.

**Comment by csperkins** [comment]
See also #109 and #110

**Comment by britram** [comment]
Revisit after #153 closes.

**Comment by mwelzl** [comment]
I note that the restructuring in #153 has eliminated my question about notification about soft errors - it's no longer available for a preconnection ("will you need soft errors?" - that sort of thing), and that was a reasonable decision. So only the "suggest timeout to the peer" thing remains.
