### ISSUE TITLE
Types: Connection vs Connectable

### ISSUE THREAD

**Issue by csperkins** [taps-api/drafts#42]
The API and architecture conflate the concepts of a Connection and a Connectable. These are distinct, and the allowable operations on each are different. They should be represented by two different types in the API and architecture. This is a problem with BSD Sockets, and something we should avoid in the transport services architecture.

A `Connection` is something on which you can send data; something that has active protocol state. It supports operations such as `send()` and `close()`, and generates events such as `Received<>`. 

A `Connectable` is something that can be used to generate a `Connection`. It doesn't have an active transport protocol. It supports operations such as `setParameters()` or `connect()` (the latter being a method that consumes a `Connectable` and returns a `Connection` object). 

These are logically different types, and should be represented as such. It doesn't make sense to call `send()` on a `Connectable` or `setParemeters()` on a `Connection`, for example. 

In pre-establishment, we work with `Connectable` objects. Establishment then becomes the process of generating a `Connection` from a `Connectable`. Once we have a `Connection`, we're in the data transfer phase. 

Discuss.

**Comment by britram** [comment]
From an architecture standpoint, I really like this.

From an API-weirdness standpoint, I have to think about it for a bit before I decide whether I like it or not... You're right that this is a bit of ugliness we inherited from socket(), and I think I've internalized it so much that 

(For some reason, the name "Connectable" really puts me off -- it feels like an extremely cheap, plasticky, off-brand, not-really-compatible-with-Lego building toy. Maybe we should call it a connection specifier? (And leave it to the Java implementation to call it a ConnectionFactory for idiom-compatibility ;) )

**Comment by csperkins** [comment]
`Listener` is a ConnectionFactory :-) `Connectable` is something a little different: it doesn't create connections, it gets turned into a connection.

And, yeah, I'm open to suggestions for a better name, but let's paint the bike shed after we agree that we want a bike shed.

**Comment by britram** [comment]
I'm pretty sure I'll admit I want a bike shed tomorrow.

**Comment by csperkins** [comment]
And a pony. Don't forget the pony.

**Comment by tfpauly** [comment]
I agree that a pre-established connection is a quite different beast for interaction from the established connection. However, for API and implementation purposes, I think separating the objects themselves, rather than just separating out what the API contract is at a given point, may be problematic and limiting.

The way I think about it, which is my biased-by-sockets view likely, is:

- As you specify your local & remote endpoints, and preferences/parameters, there is no Connection yet, just the endpoints and parameters.
- When you create the Connection, you create it with the endpoints and parameters; from that point on, those are immutable.
- When you call Initiate(), you essentially wait for Ready before expecting any ability to read and write

However, fast open (and just being efficient) caused us to allow sending and receiving prior to the Connection state becoming Ready. This allows fast open protocols to get sends early, but it also is beneficial for performance to pre-schedule your sends and receive callbacks, rather than waiting for a Ready event (which may require thread hops, etc).

If there's a one-to-one correspondence between a Connectable and what ultimately becomes a Connection (despite the fact that there may be many candidate transport stacks in the establishment phase), I'd rather have a single handle in the API.

**Comment by britram** [comment]
To some extent, the Connectable/Connection split in the API looks like a good idea all the pre-establishment things you can do on a Connection look like method calls, and calling these methods after establishment is a runtime error:

```
Connection := NewConnection()

Connection.SetRemoteEndpoint(remote) // implied by §5.1, which I'm not a fan of, after applying #43
Connection.SetLocalEndpoint(local) // ditto

Connection.Prefer(SomeTransportParameter) // see discussion in #34
Connection.Avoid(SomeOtherParameter)
Connection.Require(AThirdParameter)

Connection.Initiate() // and you can only ever do this once
```

If you're one of those Haskell strong-typing type people, this is a cardinal sin. 

With a language that has the same features as the one we're assuming with our notation (something Go-like, without either method signature munging or optional named arguments), you could do something completely different:

```
parameters := NewTransportParameters().Prefer(x).Avoid(y).Require(z)
security := NewSecurityParameters().AddIdentity(x).AddPrivateKey(y)
remote := NewRemote().WithName("www.foobar.com").WithService("https")
local := NewLocal().OnNamedInterface("en1")

Connection := NewConnection(parameters, security, remote, local)
```

i.e., the Connectable becomes the set of (mutable, and copied into the connection as opposed to referenced by it) specifiers, and the Connection itself loses all its icky "you can't do these things after connecting" actions.

Actually, while writing this, I've decided this is the pony in the bike shed that I want.

**Comment by britram** [comment]
I like this bike shed so much I painted it myself: see [the postsocket API spec in Golang](https://github.com/mami-project/postsocket/blob/master/api.go), now ported over to this terminology.

(This isn't complete; specifically, it needs more godoc, there are some security parameters fixmes, the parameter enums aren't there, and termination isn't done. But it's a start, and I'm swapping this out for the day...)

**Comment by mirjak** [comment]
I agree with Colin because I think we still need an object we can work on in the pre-establishment phase which could actually trigger some preparation actions. Brian, in your example implementation I think that is what you need the Rendezvous for but their might be even more things you'd like to do in future (e.g. crypto-sep like pre-loading of security context).

Maybe that would look like this:
``` Connectable := new Connectable(parameters, security, remote, local)
if (Connectable.rendezvous()==true)
  Connection := Connectable.initiateConnection() ```

Not sure if that makes sense, but others are welcome to propose something else!

**Comment by britram** [comment]
yeah, I'm not *quite* sure yet how Rendezvous fits into all this (paging @csperkins to go have a look at #6 :wink:)... but the fact that we seem to be converging on the point that Remotes and Locals are probably separate (see #43) and they themselves can be bound to some underlying context allows preparation to happen before `Initiate()` or `Rendezvous()` is called... 

It seems like what we need for that case is some way to tell the pre-establishment Objects how they're likely to be used together. Grouping them into a Connectable would indeed be one way to do that, but there are others as well. For example, giving a Remote a pointer to a set of transport parametersat creation  (i.e. `Remote := NewRemote(TransportParameters)` in our notation) would be sufficient for resolution. Indeed, remotes for rendezvous probably need some information about discovery and relay servers, so that might be enough of a hint...

Cryptosep is different; SecurityParameters already has a way to preshare a key, and we should probably add a way to save/restore resumption parameters as well.

**Comment by mirjak** [comment]
For both, rendezvous and crypto-preload you need to know the remote and the local as well as some of the parameters as this restricts which protocols you may use later. SecurityParameters allow you to set the key if you already know the key in the application, it does not trigger to pre-negoatiate crypto context because you already know that you are planning sooner or later to talk to a certain server. 

Btw. I still don't see where such long term state is stored in the current architecture. I still think there is something missing here but that's probably a different issue.

**Comment by britram** [comment]
We're all getting distracted it seems. :)

>> The potential issue with this style of API is that there's no way to refer to the Connectable, i.e., the equivalent of an instantiated but unbound and unconnected socket.

Yep. I was trying to decide whether it was okay to model this as a bunch of parameters/remotes/locals bound to the underlying Context that maybe know about each other, or do we want to just bind these all up in one thing ("ConnectionSpecifier")?

It seems like this is most useful when it also (optionally) contains remembered or preloaded state about past interactions using the same parameters for the pair of endpoints; in other words, as @mirjak points out, it feels like we're reinventing Post's Association.

**Comment by csperkins** [comment]
I'm not sure `Connectable` is the same thing as Post's Association; it seems more ephemeral than that. I could certainly imagine some sort of association cache could be used to derive the parameters for a Connectable.

**Comment by abrunstrom** [comment]
Is this a practical or mainly conceptual issue? The conceptual difference seems clear, but as we want to send on the Connectable before Initiate for the 0-rtt case things anyway gets conceptually messy, so then maybe it is not worth the separation. If it is needed to get the ICE scenario working that seems like a different thing. But then we need to be able to send on multiple Connectables at once or?

**Comment by britram** [comment]
The conceptual reason to split the pre-establishment and establishment objects is that it's ugly to have things which mutate and lose methods through that mutation. (The practical reason to do this is that it leads to buggy code, I guess)

The practical reason to store this in a single object, as opposed to just keeping them separate and only bringing them into a Connection when you're ready to initiate the connection as I propose above, is that the runtime might want to know which remote is going to be used with which transport and security parameters to "pre-flight" connection establishment.

Of course, you can also achieve this by using the API as above, then creating a Connection, but not initiating or listening on it; the Connection still has "connected" and "not connected" states, but remains immutable.

**Comment by csperkins** [comment]
@abrunstrom I don't think we want to send on a `Connectable` for the 0-rtt case. Once the object is in the state where you can send data, even 0-rtt data, you have a `Connection`. 

For ICE, I think we need the ability to query the possible candidates that you can connect on. That is, to get a set of `Connectable` objects that we can later pass to `initiate()` to tell it to start connection racing. The reason we need to expose the connectables is that you need to pass the list of candidates to the peer via the signalling protocol, potentially long before starting the connection racing (indeed, if you're doing ICE for SIP and the call is declined you may never initiate the connections, but you still need the set of connectables).

**Comment by csperkins** [comment]
I'll prepare a pull request to make this concrete, but looking at my schedule for the week this won't be until Friday at the earliest.

**Comment by tfpauly** [comment]
@csperkins, thanks for the explanation regarding the one-to-one question. So, if I understand correctly, the point you're making is that there many be many Connectables for a single ultimate Connection—essentially, the Connectable is a way to represent a cohesive set of connection possibilities (endpoints + parameters).

I think that makes more sense than what my original impression was. We've had some use cases in our implementation to do a similar thing, and way we've done that is to define an array of transformations within the parameters object; an example of a transformation would be "try Remote B instead of Remote A, and when you do, also use Properties B". I agree that it's cleaner to have potentially separate objects to represent the options here.

For a case in which there is only a single connectable set of Remote + Local + Properties, I'd like to ensure that it is still easy for an application to create a Connection somewhat directly (a convenience initializer to instantiate a Connection with the components of a single Connectable, rather than having to create a Connectable just to immediately create a single Connection from it). Giving a set of Connectable options would be the more full and advanced approach. Is that fine with everyone?

I'd also like to see Initiate() remain on the Connection object, since it seems that we really want the flow to be:
- Create set of N Connectables (sets of endpoints and properties)
- Create a Connection using one or more Connectables as the ones it wants to actively try
- Initiate the Connection, which starts racing

**Comment by csperkins** [comment]
@tfpauly makes sense to me

**Comment by mwelzl** [comment]
FWIW, I really like where all of this is going

**Comment by britram** [comment]
@tfpauly @csperkins thanks for this exchange, I understand the concept now, and I think it's the right way to go.

Alas, I'm going to have to bikeshed on the name, I'm afraid. I can't not dislike "Connectable".

ConnectionSpecifier (which will invariably become ConnSpec for short)? ConnectionTemplate (ugh)? Preconnection?

**Comment by tfpauly** [comment]
Ah, naming.

I like Template best of the options here. It's kind of the bundle of Properties, but that's already used. Prototype?

**Comment by britram** [comment]
Template will confuse the C++ people, though that might be a feature.

**Comment by britram** [comment]
I'm writing up the (full, general) interface for this in the Go sketch now. The slice-of-Connectables  thing makes this not very pretty at all (i'm calling Connectable `ConnectionSpecifier` here, and `TransportContext` is the toplevel)

```go
type TransportContext interface {
  NewTransportParameters() TransportParameters
  NewSecurityParameters() SecurityParameters
  NewRemote() Remote
  NewLocal() Local
  DefaultSendParameters() SendParameters

  NewConnectionSpecifier(rem Remote, loc Local, tp TransportParameters, sp SecurityParameters) ConnectionSpecifier

  Initiate(ch ConnectionHandler, specs []ConnectionSpecifier) (Connection, error)
  InitialSend(ch ConnectionHandler, specs []ConnectionSpecifier, content interface{}, ) (Connection, error)
  Rendezvous(ch ConnectionHandler, specs []ConnectionSpecifier) (Connection, error)
  Listen(ch ConnectionHandler, specs []ConnectionSpecifier) (Connection, error)
}

type Connection interface {
  Send(c interface{}, sp SendParameters) error
  Clone() (Connection, error)
}

type ConnectionHandler struct {
  Ready    func(conn Connection, ante Connection)
  Received func(content Content, conn Connection)
  Sent     func(conn Connection, contentref interface{})
  Expired  func(conn Connection, contentref interface{})
  Error    func(conn Connection, contentref interface{}, err error)
  Frame    func(content interface{}) ([]byte, error)
  Deframe  func(in io.Reader) (Content, error)
}

```

Since the `[]ConnectionSpecifier` -- the group of all possible combinations of remote/local/params -- is the thing you actually want to invoke the Initiate (etc.) actions on, it probably makes sense to make that high-level, instead (and now we need a better name)

```go
NewConnectionSpecifierSet() ConnectionSpecifierSet
type ConnectionSpecifierSet interface{
  AddSpecifier(rem Remote, loc Local, tp TransportParameters, sp SecurityParameters)
  Initiate(ch ConnectionHandler) Connection
  InitialSend(ch ConnectionHandler, content interface{}, sp SendParameters) Connection
  Rendezvous(ch ConnectionHandler) Connection
  Listen(ch ConnectionHandler) Connection
}

```

That `InitialSend` ugliness is there because there's no such thing as a Connection that isn't either setting up, connected, or closed -- this API has the advantage that you don't have magic morphing states. Of course, you can get rid of it by moving all of the state calls back into the Connection itself, and the Connection itself then becomes the natural container for the connection specifier set; i.e., exactly what this issue started off saying we don't want. But it's IMO aesthetically nicer.

```go
type TransportContext interface {
  NewTransportParameters() TransportParameters
  NewSecurityParameters() SecurityParameters
  NewRemote() Remote
  NewLocal() Local
  DefaultSendParameters() SendParameters

  NewConnection(ch ConnectionHandler) Connection
}

type Connection interface{
  AddSpecifier(rem Remote, loc Local, tp TransportParameters, sp SecurityParameters)
  Initiate()
  Rendezvous()
  Listen()
  Send(c interface{}, sp SendParameters) error
  Clone() (Connection, error)
}
```

I don't like the type-uncleanliness of this. But I suspect we might be rediscovering why sockets have the same kind of type uncleanliness.

**Comment by britram** [comment]
One more try to make this prettier then I'm done for the night:

```go
type TransportContext interface {
  NewTransportParameters() TransportParameters
  NewSecurityParameters() SecurityParameters
  NewRemote() Remote
  NewLocal() Local
  DefaultSendParameters() SendParameters

  // with explicit preconnection: start doing things you might need to do for this set of params. 
  // you need at least one, so you can't create an empty Preconnection
  Preconnect(ch ConnectionHandler, rem Remote, loc Local, tp TransportParameters, sp SecurityParameters) Preconnection
  
  // "shortcuts" for use without preconnection
  Initiate(ch ConnectionHandler, rem Remote, loc Local, tp TransportParameters, sp SecurityParameters) Connection
  Rendezvous(ch ConnectionHandler, rem Remote, loc Local, tp TransportParameters, sp SecurityParameters) Connection
  Listen(ch ConnectionHandler, loc Local, tp TransportParameters, sp SecurityParameters) Connection
}

type Preconnection interface{
  AddSpecifier(rem Remote, loc Local, tp TransportParameters, sp SecurityParameters)
  Initiate() Connection
  InitialSend(content interface{}, SendParameters sp) Connection
  Rendezvous() Connection
  Listen() Connection
}

type Connection {
  Send(c interface{}, sp SendParameters) error
  Clone() (Connection, error)
}
```

Actually, that's not that bad. I think I can live with that.

**Comment by mirjak** [comment]
I'm not sure that is what we want or need, however, Colin, correct me if I'm wrong! I don't think you would give multiple <Local,Remote,Parameter> inputs to the Preconnection. Instead if you e.g. call Preconnection.Rendezvous() this could internally create multiple connections (not sure if they would even needed to be returned/exposed to the app or not). If you then call Preconnection.Initiate() this returns you exactly one oft theses connections that have been reestablished. At least that was my thinking...

Regarding naming, I guess I'll nominate "Preconnection" :-)

**Comment by britram** [comment]
Preconnection is what I've settled on in the API sketch, because `Preconnect()` is quite descriptive of what's actually happening.
