### ISSUE TITLE
Types: local and remote endpoints

### ISSUE THREAD

**Issue by csperkins** [taps-api/drafts#43]
One of the things Post Sockets did was to separate `Local` and `Remote` into distinct types, rather than having a single `Endpoint` type. I think this is a useful distinction, that we should re-introduce it into the Transport Services API, since the two types are not interchangeable in the API calls. 

Examples:
* In Section 5, the `NewConnection()` call doesn't take two `Endpoints`, it takes a `Local` and a `Remote`.
* In Section 5.1, the allowable operations on `localSpecifier` are different to those on `remoteSpecifier` (the interface can be specified for the local, but not for the remote). 

I'm not much tied to the names, but I think it important that we distinguish logically separate types in the API and architecture. 

Discuss.

**Comment by britram** [comment]
I noticed this in §5.1 too, and agree we should separate these back out.

We should also make it clear that, for the most part, Local specifiers are most useful in server contexts -- where you really do care which specific ports and addresses are -- while in client contexts it's more useful to let the path selection properties fetch you a reasonable Local.

**Comment by tfpauly** [comment]
From the architecture perspective, I still find it useful to have a superclass concept for the subclasses of Local and Remote. How about in the architecture, we leave Endpoint, but add Local and Remote and types of endpoints, and let the API reflect that distinction?

**Comment by philsbln** [comment]
When writing $5.1, I first had them separate but soon realised that all operations I wrote can be applied to both.
For those who disagree at first glance, keep in mind that even SetInterface on RemoteEndpoints has its use for link-local and interface-local communication.

Whether we say Local and RemoteEndpoints are subclasses of Endpoint or they are the same Class used in different ways I don't care. I just don't want to duplicate common functionality.

**Comment by britram** [comment]
> but soon realised that all operations I wrote can be applied to both

so this gets into a philosophy-of-languages discussion pretty quickly, which I'd like to avoid, but simply because two things have the same action does not mean they are the same kind of thing. 

First, local and remote resolution happen completely differently -- although Locals must also keep around all their unresolved information in case the device roams onto a different network and new local endpoints/interfaces/addresses become available dynamically. The system might want (need) to know whether an Endpoint is intended for Local or Remote use before it's bound to a Connection (see #42 for why this is necessary) for resolution hinting purposes.

Second, the contracts for multiple value usage of Locals and Remotes are different; multivalue Locals mean "try all of these on Initiate; listen on all of these on Listen", while multivalue Remotes mean "here is your candidate space".

Third, they're not even really the same thing from a ducktyping perspective: I would argue (and do in the [present API sketch](https://github.com/mami-project/postsocket/blob/master/api.go)) that .WithInterface() really doesn't belong on Remote at all.

**Comment by philsbln** [comment]
Ok - you convinced me about the first two – most operations do completely different things.

On the third one, I disagree.  When I want to reach a host on its link-local address reachable via en0, the following is semantically right:

~~~
re := Remote()
re.withAddress(fe80::dead:beef)
re.withInterface(en0)
con := Connection(nil, re, parameters)
~~~

This becomes obvious, when I do the same, but instead of specifying the address and interface, I use a bonjour based host name. 
The interface for the LL address comes from bonjour and thus is part of the remote, not the local endpoint specifier.

**Comment by britram** [comment]
That's not an interface, that's an IPv6 Scope ID, which is properly treated as part of the address.

**Comment by mirjak** [comment]
Question is what would be implemented in the endpoint superclass that is applicable to both local and remote? I don't see anything here. @tfpauly , do you have further insights?

**Comment by philsbln** [comment]
@britram That depends how you define the address or address representation. 

Most implementations differentiate between scope-id (equals interface index) and interface name.

- If we explicitly define address to include address to include the scope ID which can be represented by an interface name, I am fine to remove withInterface from the remote address.
- otherwise, we should rename withInterface to withScope and accept interface Names as scopes

not sure if we are already in the implementation…

**Comment by britram** [comment]
(FWIW: https://golang.org/pkg/net/#IPAddr )

**Comment by tfpauly** [comment]
@mirjak I think there are parts of Endpoint that are in the superclass—they may seem rather trivial, but they're useful for implementations to deal with.

Essentially, we need a type to represent either an Address + Port, a Hostname + Port, a DNS Service Name, etc. Being able to have a base class that can be used for comparison, etc, is very useful—is this local endpoint actually the same as this other remote endpoint, because I'm going over loopback or something similar.

Also, while the case of a IPv6 scope ID is not really an interface being added to an endpoint, but a property of the address itself, we do in fact have cases in which we tag endpoints with the interfaces (or PvDs) that they are relevant on. This is mainly useful for locally discovered DNS services. I can resolve a service like "Tommy's Tunes._music._tcp.local.", and get multiple Hostname + Port results, each that was resolved locally to a different interface, and which will ultimately use a different address. So, tagging an interface isn't really an operation we let the application do when creating connections, but it can happen internally during the course of resolution.

**Comment by britram** [comment]
question then is, do we explicitly expose that superclass relationship in the API, or do we let the implementation figure that out on its own?

(In the current Go sketch, it's obvious that you could/ should share much of the low-level implementation, even having Local and Remote just be interface-mediated views on the same underlying struct type, but that's just an artifact of how Go does interface typing)

**Comment by csperkins** [comment]
If the only common feature is that `Local` and `Remote` can be compared, then I'd argue that we should just document that and leave it to the implementation how it's implemented. If there are API calls that can take or return _either_ a `Local` or a `Remote` then we should likely mandate a common supertype.

**Comment by tfpauly** [comment]
It's not just comparison, though. Unless we expect people to use sockaddr structs (please no) and direct hostname strings and port integers, we need some wrapper type to hold the contents of endpoint names and addresses.

**Comment by mirjak** [comment]
To me this sounds like we sounds have Local and Remote as the architecture object and the common superclass is just an implementation detail...
