### ISSUE TITLE
Inform Application about TransportStack and Pseudo-Transports

### ISSUE THREAD

**Issue by philsbln** [taps-api/drafts#47]
This is a fork of what is left from #27.

Protocol Selection and Connection racing  lead to different stacks.
The application needs to be able to introspect what it actually used to connect and whether a pseudo-transport like HTTP is provided by the transport system.

- Where is the best place to inform the application? Possible Places:
   - Only allow introspection on the Connection
   - Pass it to the Ready / ConnectionReceived event
   - Make it part of receive 
- If pseudo-transport are more than framers, how to extract the protocol information?

**Comment by mwelzl** [comment]
Hm, I think there are MANY things that an application may want to ask about. The easiest and most flexible way to handle this seems to me to just offer a "status" primitive that's associated with the Connection, and that an app can call whenever it wants, in whichever phase it want. "Status" returns a data structure. We can define the minimum contents of this data structure as a list somewhere. We can start by including the chosen protocol, the chosen interface, ...    does this make sense?

**Comment by theri** [comment]
Having a "Status" primitive sounds good to me, though Connection.getProperties() in Section 9 (Maintenance) goes in the same direction.
Pre-Establishment, "Status" could return that the Connection is not opened yet, maybe the TransportParameters, and perhaps some Protocol Stacks that might be tried later. I think we need these Protocol Stacks here already, because otherwise I don't know how an application can query "Maximum Content Size Before Connection Establishment". I suggested having such a list of protocols available in the Implementation draft in §3.1, because the implementation should realize as early as possible if there are no protocols that it can try, e.g., due to impossible requirements from the application.
On Initiate(), it could return something on the Candidates that are being gathered and raced, but not sure how much we want to expose to the application there - maybe just the "phase" that the implementation is currently in (i.e., Gathering or Racing in progress)? I'm sure there can also be such as status label after Listen() or Rendezvous().
And then finally after a Ready<> event, the application can query the actually chosen Protocol Stack, which I called Protocol Stack Instance in Appendix A.2, which is bound to the Connection, and also the Connection's Path(s).
We could pass this information also in the Ready<> Event, I think, to make it more convenient for applications that care, but maybe that's too much. I definitely wouldn't make it part of every Receive.

**Comment by philsbln** [comment]
Looks like we all agree on a general direction. (Just had a phone call with @theri)

- We should have a ``Connection.GetStatus()`` call that returns some Object to introspect the status of the connection
- We should also have a ``Connection.GetParameters()`` call that just returns the ConnectionParameters Object
- Maybe rename the *Maintenance* section into *Introspection*
- Adding the Status Object to Receive or Ready events seems superficial, because we have a connection reference there and  can all getStatus on it.

I think we can wait with writing the API part after @mwelzl has finished the corresponding part in the Implementation. @theri and I can do this together.

Final Question: is this for London or post-London?

**Comment by mwelzl** [comment]
I think a first stab should be for London; and I don't care at all about the name (FWIW, Connection.getProperties sounds better to me than "Status").

What I do think is that we shouldn't have separate calls but just one which, as Theresa suggests, will be able to return much less information in pre-establishment (i.e., I don't think we should have a separate call "just returning the ConnectionParameters object" - let's rather have one that generally gives us everything an app may possibly want to know, I can't see any negative sides to this and it seems simpler).

About what exactly we offer with "getProperties" (can we agree on that as a name?), I think we should, for once, really begin small: what's the absolute minimum that we think applications should be able to learn per phase?    I think this is a very obvious case for implementations going beyond the standard - surely implementers will just dump whatever they think is useful for app programmers here. And that should be fine!  The more the merrier!  What we need to do is to ensure that they don't miss including the things that we write up.

**Comment by theri** [comment]
Alright, the "Status" can just be one property that the application can get using Connection.getProperties() then.
Other things the application can get are the Transport Parameters that it specified in the beginning, the Protocol Features of the actually chosen protocols, and the Protocol Properties we define in 5.2.2. I think the question of what exactly the application can query and when is also answered in Appendix A.2. Agree that there can be more, e.g. Path Properties, but at the moment I don't see that we have to standardize these Path Properties, at least not pre-London.
About renaming the section to Introspection I'm not sure - doesn't that imply read-only? But the application can also set Protocol Properties on the connection. Perhaps a call for this should be included in that section as well.

**Comment by mwelzl** [comment]
I think I just agree 100% with everything @theri wrote here

**Comment by philsbln** [comment]
- We need to model ConnectionProperties then, including
   - reference to ConnectionProperties
   - reference to ProtocolStack (and model Pseudo-Transport there)
- I think we do not need a separate call to set ProtocolProperties – modifying the TransportParameters object accessible through the ConnectionProperties should be sufficient.
- Keeping PathProperties for post-London is fine with me

**Comment by britram** [comment]
For me, Introspection doesn't necessarily mean read-only. "Introspection" or "Reflection" is commonly used to describe the programming language feature that lets programs muck around with the language internals, so this 

I also agree that we should specify *what* the minimum set of information the API must make available, though not necessarily *how* that should be represented (since sometimes this will be determined by the language/platform idioms). @theri's suggestion here seems good to me (though, echoing @philsbln, I do think we need at least to allow the application to see the selected stack instance(s) in the established phase.

**Comment by theri** [comment]
Feel free to comment or extend, and/or close this issue.

**Comment by gorryfair** [comment]
- Can we just call the section “Setting and Querying of Properties”?

**Comment by theri** [comment]
Works for me.

**Comment by gorryfair** [comment]
Oh - and I agree with one call to get the conenction infromation.
I think we should specify the first parameter as the state of the conenction.
The rest I think we need to keep simple to start with.

**Comment by britram** [comment]
this seems done to me...
