### ISSUE TITLE
Do we need an indication that the application will not send any further data but is still willing to receive data (aka EndOfData())?

### ISSUE THREAD

**Issue by mirjak** [taps-api/drafts#53]
As discussed with PR #49 we need to decide (post-London) if we want an EndOfData() call. It was noted that this is not supported by all protocols and that TCP's close() mixes things up wrongly. Therefore EndOfData() must be separate from Close() and might not have any effect if not supported by a certain protocol.

**Comment by gorryfair** [comment]
My first reaction is that close and abort are the correct primitives here. 

Drilling into to details (TCP, SCTP/UDP, etc) is unlikely to be a useful thing in this spec. If we were to specify the semantics correctly, we do not need an additional primative. My fealing is probably flavoured by the belief that applications should anyway decide at a higher level that they have finished communication before they issue close, and not rely on a callback to do this  - anything left in the transport on calling close is unlikely to make it to the endpoint.

**Comment by tfpauly** [comment]
I agree with Gorry that we can just use Close and Abort as top level Connection API calls.

However, for Send(), I currently pass { Content, Metadata, isComplete, Callback } as parameters. The isComplete indicates if the Content is a full chunk for a message. When used over a streaming protocol like TCP directly, TCP can choose to interpret this as an indication to send a FIN. That replaces the notion of write-close for us.

**Comment by mwelzl** [comment]
But the description "open, send, close" doesn't capture what this issue is about: "... will not send any further data but is still willing to receive data". write-close per se isn't a problem, but the "still receive" part is problematic. I also don't understand Mirja's statement that TCP's close "mixes things up wrongly" - I think TCP, and perhaps only TCP, gives you exactly what you want ("...will not send any further data but is still willing to receive"). SCTP is a counter-example, as it doesn't support half-closed connections, and the same is probably true for streams that are used as connections.

Anyway: if we want to support "will not send any further data but is still willing to receive", we need to understand how this should work. I can imagine that, with a protocol that doesn't support half-closed connections, the transport system sends, remembers (above the transport) that the application is done sending, and the connection is kept open so the application can still receive, until .... when?  Who truly closes the connection, when? The other side?  I think that makes it application specific. I think it would work like that with web servers, though.

**Comment by tfpauly** [comment]
I'd like to resurrect this for discussion in -01.

**Comment by tfpauly** [comment]
The place I'm currently at with how to express sending a half-close is this:
- Mark a property on the Message that it is the "final" message
- Once that Message has been completely sent, the application has indicated it is done sending on that connection
- Marking "final" on a Message's context implies that you want this message to be last if there is any sorting to do for niceness/priority/etc.
- When receiving Messages, the receiver similarly can check the "final" property of the received Message to see if this is the last message that will be received

This allows the API to work just fine with TCP FINs, but also has the nice property of allowing many messages to be sent and received over a connection, while providing a way to signal that a set of Messages is complete.

**Comment by tfpauly** [comment]
Closing now that the PR is merged
