### ISSUE TITLE
API Section: 8.1. Application-Layer Back-Pressure at the Receiver

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#55]
This text /Implementations of this interface must provide some way for the application to indicate that it is temporarily not ready to receive new Content. Since the mechanisms of event handling are implementation-platform specific, this document does not specify the exact nature of this interface./

- I believe this is actually an example of a function that is provided by an APP. I really suggest we should avoid providing “hooks” for APP signalling in the transport. That’s been proposed in many transport systems in the past … and it often ends up messy. I’d advocate telling the APP to implement the function itself!
- Backpressure (flow control) is a classic example of what can be hard to realise, X.25, ATM, and more recently HTTP all tried and failed to make this a deadlock-free useful function!
- I suggest we discuss this or remove it from the draft.

**Comment by tfpauly** [comment]
I agree that this text should be removed. The application should not indicate that it is not able to receive content—that seems to imply sort of blocking semantics.

The way I prefer to think of it is simply that, in order to provide natural back pressure between the stack and the app, the act of Receiving is a "pull" model, rather than a "push" model. The application pulls up data from the stack to receive as necessary, by scheduling a callback to receive content in. The stack does not simply deliver content into a recurring callback over and over (which eliminates back pressure). While the act of scheduling the receive callback (to "pull") does indicate that the application is no longer unable to receive, this is a difference from explicitly indicating when it is not able to receive.

**Comment by britram** [comment]
So this implies making the Receive<> event special, in that you need to re-register for it each time... Okay, I buy that, will make this change in my omnibus edit pass (hopefully tomorrow, running out of time a bit...)

**Comment by tfpauly** [comment]
I think it's no less special than a callback event for Send completion. 

For Sending, you get a Send Complete event for *that* particular Send. It won't fire magically, it's one-to-one with each call to Send().

Each call to Receive can/should be decorated with constraints on the read—only read up to this much, or make sure you read a complete message/chunk/frame. So, the completion for the receive matches what was requested. For our implementation, there is a callback block that can be different for each invocation of Receive() in case it needs to go to a different codepath.

Essentially, any event needs to have a contract of how it can repeat. For memory management reasons, it's important to know that there is a one-to-one call-to-callback correspondence if you want to allocate something in the call, and free it in the callback; or that an event can fire any number of times, which requires different handling.
