### ISSUE TITLE
Section 5.2.1. Choice of Title: Transport Preferences

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#58]
(1) I think this function can also express a requirement, and I suspect this is also the case here, since I think you can prohibit certain types of interface/path, or require a corporate network PvD, or …  etc. Is this actually the case - can we say so?
(2) I think if (1) is true, “preferences” is a rather weak word to describe what can be requirements. We suggested “properties”, but maybe that is thought of as something else. If we need to, can we say "Transport Preferences and Requirements"?

**Comment by britram** [comment]
(1) These are indeed both preferences and requirements (as is clear from the preference levels table after the first three paragraphs).
(2) I'm not really inclined to change the title, though... the construct "Preferences and Requirements" would for parallelism have to be repeated throughout the text, which is a little clunky, and these really are preferences in the sense of a set of things the application expresses to the interface... sometimes that preference is "I don't want connectivity if you can't give me these properties."

**Comment by theri** [comment]
Yes, these properties can be something the application Requires, Prefers, [wants to] Avoid, or Prohibits. 
I think we were discussing an "umbrella term" for these preference levels in #28, since "Priorities" does not work, but so far failed to come up with a better term than Preferences.
I agree with Brian that always naming two of these levels, or even more, will get too clunky.

**Comment by gorryfair** [comment]
OK, I agree that.

Could you add a single opening sentence in this subsection that says this contains bothe preferences and requirements. That almost certainly would have avoided my comment:-)

**Comment by tfpauly** [comment]
+ 1 to making it clear that there are preferences and requirements.

I do find it a bit odd to have Transport Preferences include Path Properties and Protocol Properties—the architecture separates those out, since they are used by the implementation pretty differently, and it may make sense to eventually have different sub-categories here. I guess I'm not sure what the "Transport" part is referring to: the transport protocol behavior, or the network-as-a-transport.

**Comment by theri** [comment]
I think at this point it potentially refers to both. Some preferences may indeed influence both, such as specifying multipath behavior (failover VS use in parallel etc), or Intents. But I agree that most Transport Preferences can be neatly sorted into either Protocol or Path selection properties and the draft should reflect this somehow, maybe by re-introducing separate headings. But then naming the third "May be both" category can get awkward...

**Comment by tfpauly** [comment]
Yes, we don't want an "Ambiguous" category. Perhaps just naming this differently than "Transport" would be useful.

**Comment by abrunstrom** [comment]
Why are we not sticking to the terminology agreed on in the architecture draft? Most of the terminology for pre-establishment in the API draft seems to be out of sync to me? What is called Transport Preferences is mostly what we have referred to as Protocol Selection Properties in the architecture + a few Path Selection Properties. Why not use that agreed on terminology and get rid of all other new inventions? We know some properties will influence both path and protocol selection, but agreed they could still be mapped to their main topic (Alternatively we need to rework the architecture document, but that would not be my preference.)

**Comment by tfpauly** [comment]
I agree that the sections in the architecture are fairly simple to explain and list here, and we can move out anything that doesn't fit to the appendix for now.

**Comment by britram** [comment]
...okay, so what's the suggested change to the section now? Rename "transport preferences" to "protocol and path selection properties", make it clear earlier that these cover preferences and requirements (keeping the require/prefer/avoid/prohibit terminology")...anything else?

**Comment by gorryfair** [comment]
That would sound good to me. 
- If the open sentences start to explain what comes in the section, I'd think it would be lovely;-)
A good phrase from the Arch reads: ... Path Selection Properties, Protocol Selection Properties, and Specific Protocol Properties influence the choice of transport that a Connection will use.

**Comment by abrunstrom** [comment]
Sounds good! Not sure if we want to separate Path Selection Properties and Protocol Selection Properties into separate subsections or not? Perhaps it depends on how many we have in the end.

**Comment by philsbln** [comment]
I would not separate them again as the distinction between Path Selection Properties and Protocol Selection Properties is not sharp.

The distinction between Transport Preferences and Intents/Protocol Properties was made based on their type – whether they are a preference (require/prefer/don't care/avoid/prohibit) or something else (Boolean/Enum/Int) – which is a different perspective than the one in the architecture.
I choose the term "Preferences" because I still see this as a level of preference including "I'd rather not communicate if by xxx is met / not met", but I am not bound to that term.

This was the least weird/contradictory/overlapping categorisation I found for the given set of properties.

**Comment by britram** [comment]
agree that protocol and path properties cannot be separated. However, one way to make this section less weird would be to move the *protocol properties* out of preconnection, as @mwelzl suggests in #69. On editing to make this happen as part of the sweep, I'm coming to agree with him, so we'll try that out...

**Comment by philsbln** [comment]
I think it is fine to have them in preconnection, but as a different beast – so having Intents and Preferences to drive the path and protocol selection magic (and defaults for the protocol paramters) and Protocol Parameters that get applied once an applicable protocol was selected.

This divide can be copied into the message api later to allow per-message path selection

**Comment by abrunstrom** [comment]
You can not move the protocol properties out of preconnection. A protocol property such as Reliable Data Transfer for instance is a Protocol Selection Property and cannot be moved out. We have Protocol Selection Properties and Path Selection Properties drive the path and protocol selection, otherwise the architecture doc needs to change. If we cannot separate them just call the section Path and Protocol Selection Properties.
