### ISSUE TITLE
API Section 5.2: Discuss types of Intents we want to standardise

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#60]
I think the following ser of related comments all concern the QoS-focus of the current text. When we discussed the formation of TAPS we decided - correctly I believe - to leave QoS out of scope, and I think this implies avoiding that the API communicates what the APP is doing, and rather communicates what the APP need/expects from the network.

—
5.2.3.1. Traffic Category
 I don’t recall discussing this, and I do not think this should be included. I really do not agree with this. I think we should restructure this as an expectation of what the network path needs to provide. Saying it is “query” and then discovering there are 500,000 queries per second isn’t helpful. Saying it is “bulk” is wrong - what is bulk to one app may be interactive to another, etc.

This I really believe needs to be expressed in terms of “low-latency”, “maximise-throughput”, etc. Things that are basic path capabilities.
-  I don’t recall discussing these below, and I do not think this should be included.:

/5.2.3.2. Size to be Sent / Received
This Intent specifies what the application expects the size of a transfer to be. It is a numeric property and given in Bytes./
- My starting point is to say “the app often does not know this” and even when it does, this is often not a useful property. 

/5.2.3.3. Duration
This Intent specifies what the application expects the lifetime of a transfer to be. It is a numeric property and given in milliseconds./
- I am OK with the concept, although I really dislike numeric parameters. Is it possible to express this as a boolean? - Maybe no, because the app has a specific deadline in mind?
- If this can’t be a boolean, can it be modified by the app as a connection proceeds? (If that is the case, I’d argue this should be anticipated end-time, rather than duration. The duration makes very little sense once the call us on-going.

/5.2.3.6. Cost Preferences/
- I can see how the proposed format for this property provides extra detail, but I believe this us problematic for a basic TAPS API.
- I suggest we replace this with something boolean - perhaps just the first /Avoid transports associated with monetary cost/ … the more depth we express in the basic API, the more problematic it is to resolve what the application is asking for against what it does and to associate a correct policy with conflicting parameters. I suggest the policy engine can more easily match this.
- The example below tries to show why I would push hard on not having a Qos_style request" with a numeric parameter:
"Consider an APP that actually knows something about the size of the objects at the point the client makes a request. And consider a network, say, that supports PvD where you know the RTT and some notion of the local path characteristics. The TAPS system can choose to use one interface rather than another.

I think the idea of switching on the "suggested" size of the transfer could be wrong. My take is that the APP should identify it prefers low-latency rather than high-thgroughput (a binary quantity) for any short transactional objects. That is a concrete thing to request from the network. 

Even if the connection is cloned/maintained for other purposes that property remains valid for all connections that are in a group.. 

I also like that if an APP asks for a policy trade-off it necessarilly will benefit or loose based on whether the connection usage matches what you request. You can't game that, which you could if say "I want to mov 20KB" and actually send "64KB" but know that some other app asks for "32KB" and that you may win in this case... etc etc.

I'd propose we carefully review the text in this section

**Comment by britram** [comment]
I'm preparing for my big edit pass, and I continue to have concerns about how a lot of the QoS-focused Intents stuff fits into the interface at this level. My current thinking (which I guess I should file an issue for) is that we should create a "Potential Extensions" appendix that points out that one of the nice things about the framework we have (with transport and path prefs to bind prefs on a per-Connection basis and send parameters to bind prefs on a per-Content basis) is that we have what is (IMO anyway) the minimal and correct set of extension points, where you could add functionality to the base standard. For -00 I'm inclined to push everything we don't have consensus on (most of the Intents, per-Content Priority/Niceness) into this appendix, which gives us the ability to have these discussions with the wider WG, without losing the work we've done on integrating them so far.

**Comment by gorryfair** [comment]
Yes. That could be a good solution for me - I think we should **ONLY** include the stuff we really agree upon in the body. However, creating an appendix for us to disucss more is good for me, because to me there are two things here:
- The socket intents work bubbles up useful ways you can judge what helps the app
- This document needs to find a "idiot-proof" way of passing sufficient useful info across the API.
- For some items - these two are subtley different.

**Comment by tfpauly** [comment]
Yes, we should definitely push anything iffy to the appendix, especially QoS. 

The things I see as solid that we can leave for now are especially ones with very deterministic path selection implications: "no metered/expensive" (but not the other balance/optimize cost options), require/prohibit/prefer interface types, allow 0-RTT.

**Comment by abrunstrom** [comment]
Whatever is left should not be called Application Intents, but rather moved to Path Selection Properties or Protocol Selection Properties I think.

**Comment by abrunstrom** [comment]
And removing to appendix sounds good.

**Comment by theri** [comment]
I agree to not include QoS in the body of the draft. However, Intents are not QoS, as the current Section 5.2.3 already reflects. Rather, they specify exactly what Gorry proposes in the initial post, as an Intent "[…] communicates what the APP need/expects from the network." It is possible to map some Intents to DSCP, such as the Category, or Timeliness of, e.g., "Interactive" or "Background", which also goes back to the "Capacity Profile" in Minset. However, Philipp and I think that Intents are much more, e.g., inputs to Path Selection and protocol configuration.
For example, we use Size to be Received as a Path Selection Property in our prototype, and Bitrate to be sent can inform protocol configuration, which would make it a generic protocol property, I think. Also, Cost Preference can be a Path Selection Property that maps to our preferences scheme of (Require/Prefer/)Avoid/Prohibit (Of course Require and Prefer do not make sense here, but as the table in Appendix B.1 shows, not all Properties make sense with all preference levels).
We are currently working on a section in the Implementation draft that clarifies these potential uses. Unfortunately we haven't been able to finalize it yet due to teaching duties or illness.

**Comment by philsbln** [comment]
Ok, now, as my fever lowers, let me comment on this.

First, I think this needs a bit clarification: All four Intents @gorryfair criticised in his initial post were primarily meant as path selection properties (also I believe the make good input into protocol selection as well as protocol tuning), not as QoS style labels.

Now some clarifications to the individual intents
- *5.2.3.1. Traffic Category* is more or less equivalent to the Capacity profile from minset. 
   It is not fool-proof, but gives some hints whether to optimise for latency or bandwidth and how to do local buffering. Even if a have 10000 small queries, this is different from transferring a 1GB blob that is only useful once fully transferred and the transport system my choose paths and protocols differently for them.
   Yes, we may need some discussion about the levels.
   We are more than happy to provide usages for the implementation draft.
- *5.2.3.2. Size to be Sent / Received*
   If an app does not know these values, it won't set these Intents. (We have more properties that at not used in the majority of cases, i.e., that is not an argument)
   In cases like MPEG-DASH / adaptive HTTP streaming, this information is known and this makes up a hell lot of traffic. 
   We find this property extremely useful for path selection: when we have bandwidth and RTT estimates, we have an idea which path will be faster (for web traffic, this is often the lowest latency path, not the highest bandwidth path). But without knowing latency and RTT, the app does not know whether the transfer will be latency or bandwidth limited. The OS has at least enough data to apply heuristics. 
   Same is true for multipath negotiation: We don't need to try to negotiate MPTCP and additional paths if we are done after 10kb anyway.
   I agree there are some problems how this combines with cloning and connection groups. I have an idea how to solve this, but not for London, as this requires the introduction of connection pools.
- *5.2.3.3. Duration*
   I guess this is _one_ way how to represent the duration of a connection, another one can be an enum like "short-lived/long-lived" - this can also be derived from Size to be Sent / Received or by other means
- *5.2.3.6. Cost Preferences*
   From my perspective, a boolean is not enough to provide hints to the transport system as the property set by the application will be interpreted by the transport system based on user configuration.

**Comment by mwelzl** [comment]
A few scattered comments about this thread:

1) The general idea of moving things to the appendix for -00: I think that's the right approach. This discussion is already at the level at which, I believe, we should discuss these matters: how exactly are we going to use these API elements, what exactly are we going to do with them. Such text should go into the implementation draft, and this text can then be input for a discussion to decide which of the intents should, for -01, be removed, remain in the appendix, or moved to the front.

2) I don't think we should even have this kind of discussion for stuff from minset. There are clear arguments for why all of them should be supported, in minset - and so, the "traffic category" intent (based on the minset "capacity profile") should really remain in place.

3) @britram : about one specific item - you wrote "For -00 I'm inclined to push everything we don't have consensus on (most of the Intents, per-Content Priority/Niceness) into this appendix"  -  I believe that you and I didn't have  consensus for a while on per-content priority / niceness because I didn't understand your idea of using multi-streaming to implement this. Now that I get it, I think it's a great idea and would clearly work, and so I think we DO have consensus on this one.

**Comment by britram** [comment]
@mwelzl ack. you'd almost convinced me it was a boutique enough feature to leave out for now. :) FWIW we (the SCION people) have been thinking of it primarily in terms of multipath architectures, not multistreaming, but both give you the degree of freedom you need to make it a meaningful signal.

**Comment by mwelzl** [comment]
I started getting second thoughts about this some hours ago, on the plane (on the way back from holiday - i.e. I'm back online) - because this needs something on the receiver side to know what you're doing, when doing multistreaming (*not* multipath). E.g., mixing connection-to-stream-mapping with this makes it really confusing: if a receiver expects 2 streams, but gets data on 4, what is it supposed to do? Streams 3 and 4 are different priorities for stream 2, or 1, or what?  So... I think this CAN be implemented but it can also make things rather complex. Anyway, my suggestion is to leave it in - and indeed, the multipath case is much easier.

**Comment by britram** [comment]
I'm digging into this now for -00; see #69 for discussion on how I plan to resolve

**Comment by britram** [comment]
@theri to review (and possibly fold into #59...?)

**Comment by philsbln** [comment]
The profiles in #59, the [generic properties](https://datatracker.ietf.org/doc/slides-102-taps-4-an-abstract-application-layer-interface-to-transport-services-properties/) and the intents discussed here are three different variants to approach the same problem:

   How to specify properties at different levels of abstraction

I guess we have to find a nice way to sort all of them, but I guess neither the perspective of this issue nor the one in #59 seems right to me. I am re-adding the discuss-label, but request to jointly discuss it with #59 and the generic properties.

**Comment by britram** [comment]
ISTM (and maybe I'm projecting here) that we're converging on the following:

1. Capacity profile probably makes sense to pull into the TAPS API, since it can map deterministically to both transmission scheduling actions as well as signaling (DSCP) and path/stack selection, even it if is very difficult to define in a not-application-specific way. I'm working on this in #142 today.

2. Other higher-level Intents are not as deterministic: to the best of our knowledge, there is still research to be done to determine the best way to implement them. It's therefore probably best to support Intents in an API that sits on top of the TAPS API, not the TAPS API itself. (It does seem to me that work on this higher-level API could happen in TAPS under the same charter item that covers the architecure/interface work, but IMO we should direct our efforts to get the three adopted documents out the door first).

3. The key determining factor for whether something belongs in this level of the API is (and I think I'm paraphrasing @mwelzl here) is: can the transport stack or the application do something unambiguous with the information it gets across the interface, and is the implementation of a given feature obvious and deterministic.

I'd suggest the following resolution to this issue and #59, then:

Let's close the big "what part of Intents comes into the API" discussion, and re-open discussion on a per-property and/or per-feature basis, using the dividing line in (3) above to make the choice.
