### ISSUE TITLE
Sweep properties/features without group consensus to a new Appendix A

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#69]
During my final editorial review pre-00, I'll take everything we're still discussing into a new Appendix A, with some text along the lines "an advantage of this framework is it has extension points for properties and preferences beyond those in the proposed standard interface; here are some potential properties and preferences that we have some design and implementation experience with that may prove useful, and may be added to the core interface in future revisions of this document."

**Comment by britram** [comment]
So far, tracking the discussion in #60, I propose the following:

- Everything in section 5.2.3 goes into Appendix A, except:
  - Traffic Category which gets lifted up into Transport Preferences (and possibly renamed Capacity Profile by reference to Minset), with additional language that (1) the only useful preference level is Prefer and (2) in addition to being used to select transports, it can also be used to configure selected transports for e.g. DSCP marking.

- The Immediate boolean send property gets removed to the appendix in favor of disabling Nagle via Traffic Category.

**Comment by britram** [comment]
(On rewriting Traffic Category as a path/protocol preference, it's not clear to me what the stack is supposed do with any of these other than the interactive/default/bulk classes. I'm leaving Stream/Constant Rate but I'm not sure what to say about it. We can fix this post-00)

**Comment by philsbln** [comment]
We are currently writing the implementation part for all Intents – text for that will appear in the intents-implementation branch in the next days

**Comment by mwelzl** [comment]
I think we ended up with a confusion due to renaming: I thought that the thing that is based on the minset "capacity profile" is "timeliness", not "traffic category". And why remove Immediate?

Actually:

- an app needs a way to say that we require low latency, even at the cost of more overhead. That can be Nagle-like Message bundling, or other things (e.g. see issue #90). Because this request may (as in the case of Message bundling) be necessary for a message, I think it would be good to keep "Immediate".

- removing this from the minset capacity profile, it only covers table 1 in draft-ietf-tsvwg-rtcweb-qos-18. I think we want applications to be able to choose cells in this table, *somehow*. I don't know how to do this most cleanly; for version -00, maybe we could simply point at this draft and say that the "Traffic Category" would choose cells in this table?  Or some such solution...

**Comment by britram** [comment]
> I think we ended up with a confusion due to renaming: I thought that the thing that is based on the minset "capacity profile" is "timeliness", not "traffic category

aaaah right. yep that makes more sense.

>  And why remove Immediate?

because capacity profile "Interactive" does this for you on a per connection basis?

**Comment by mwelzl** [comment]
Hmm. Controlling bundling is a per-message thing in SCTP, whereas TCP's Nagle is time-based. We could argue whether this should be kept per message or not... I'm not 100% sure that binding this to a message is indeed important to anyone.

=> I'm fine with your decision. Let's only have this per message once we've convinced ourselves that doing this per-message really matters.

**Comment by mwelzl** [comment]
More issues in the current text:

Section 5.2.1 Transport Preferences:
If you agree with my conclusion in issue #90, then the item "Request not to delay acknowledgment of Content" should be removed here.

Section 5.2.2. Protocol Properties:
This text:
"Set timeout for aborting Connection establishment: This numeric property specifies how long to wait before aborting a Connection attempt. It is given in seconds."
should be:
"Set timeout for aborting Connection: This numeric property specifies how long to wait before aborting a Connection (including a Connection attempt). It is given in seconds."

This is important because section 9 points back at this section, stating that these Properties can be configured later. So to have a configurable Connection timeout, this text must be about the Connection, not just the Connection attempt.

The timeout of the Connection attempt itself is also discussed in minset; I removed it as a separately configurable thing even in minset because this is really just about *when* to configure the timeout. Because an app can change it later, it can control both the establishment timeout and the connection timeout with this single Property.

**Comment by mwelzl** [comment]
RTO timeout, the application shouldn't care about. Heartbeat timeout, the application shouldn't care about (at least when I'm thinking of SCTP heartbeats ... depends on your use case I guess).

The application should only care about a Connection timeout, and then there are two phases here:
1) establishment,
2) being connected
... and we can distinguish between these two via the time of using the call.

What else is really missing?

**Comment by britram** [comment]
so I'm not clear what the "being connected" timeout is -- is this an idle timeout, i.e. an assumption that the other side has dropped state so we should too?

**Comment by britram** [comment]
actually, with respect to §9, the following:

> Protocol Properties of the protocols in use, once the Connection has been established. These properties correspond to the properties given Section 5.2.2 and can be set and queried.

is, IMO, not something we have consensus on. At least, I don't thing we should limit the Generic and Specific Protocol Properties to *only* those which are safe to change after establishment. I'd keep this "establishment" timeout, then remove it from the set of settable properties.

**Comment by britram** [comment]
(Indeed, I think we should fix this by removing "can be set" here, and noting that certain specific properties may be settable after establishment but only on a Protocol Stack and Property specific basis)

**Comment by mwelzl** [comment]
First, about the "being connected" timeout: this is not an idle timeout. In case of TCP, it's the User Timeout - which is typically more than the RTO; it's TCP re-trying and re-trying ... until this timeout expires. Hence, in TCP, at least according to the RFC, you can only change it when you send something (or with "open"). In SCTP, heartbeats are used to check for this timeout, so you can change it at any time. The way I described this in RFC 8303 / pass 2 (section 4.1), it can be issued at any time and will only take effect for TCP upon the next "send" call.

**Comment by mwelzl** [comment]
About §9, this whole current structure is currently messy - I think a clean approach would be to separate ALL Connection properties out from the current structure and not make them a part of Pre-Establishment, and then, in Pre-Establishment, say that the following ones (with a list) can be changed on Pre-Establishment. Or maybe say that "as many as possible should be set on pre-establishment".

However, it's a fact that most can be changed later. So this:

> (Indeed, I think we should fix this by removing "can be set" here, and noting that certain specific properties may be settable after establishment but only on a Protocol Stack and Property specific basis)

seems very wrong to me. You CAN change the minimum checksum requirement of an ongoing connection. You CAN change the scheduler. Why would you want to take all this functionality away?

I also don't know what "settable on a Protocol Stack and Property specific basis" means -- e.g., you can change the checksum requirement and if you use TCP, nothing happens. That's the normal fallback logic from minset.

**Comment by mwelzl** [comment]
The list in 5.2.2 contains one item that really can only be queried: "Maximum Content Size Before Connection Establishment". So it has to be taken out of this list and written separately. Else, the list seems to completely cover the list from minset, except that "capacity profile" is missing.

Also, later, on an ongoing connection, it should be possible to query:
   o  The maximum message size that may be sent without fragmentation,
      in bytes (or "not available")
   o  The maximum transport message size that can be sent, in bytes (or
      "not available")
   o  The maximum transport message size that can be received, in bytes
      (or "not available")

**Comment by mwelzl** [comment]
Someone has written this paragraph in 5.2.2 which I also don't agree with:

In order to specify Specific Protocol Properties, the application can attach a set of options to the Preconnection object, associated with a specific protocol. For example, the application could specify a set of TCP Options to use if and only if TCP is selected by the system, including options such as the Maximum Segment Size (MSS), and options around Acknowledgement Stretching. Such properties should not be assumed to apply across different protocols, but must be possible to specify if required by the application.

This invites protocol-dependent implementations... I can see that some folks may want to support such things, but at least in a PS document we shouldn't say "must be possible to specify if required by the application": what exactly must be possible to specify? All possible TCP options?  Also, "options around Acknowledgement Stretching" is a vague statement, what exactly is this even about?

**Comment by britram** [comment]
> Else, the list seems to completely cover the list from minset, except that "capacity profile" is missing.

So I've currently written Capacity Profile as a Transport Preference, not a Protocol Parameter, since a particular capacity profile may also be used in path and/or protocol selection.

**Comment by britram** [comment]
> In order to specify Specific Protocol Properties, the application can attach a set of options to the Preconnection object, associated with a specific protocol. For example, the application could specify a set of TCP Options to use if and only if TCP is selected by the system, including options such as the Maximum Segment Size (MSS), and options around Acknowledgement Stretching. Such properties should not be assumed to apply across different protocols, but must be possible to specify if required by the application.

I think this was @tfpauly -- and yes, I thought you might disagree with it. :smile:

ISTM the reality of the situation is you will *always* need an out to specifically configure the details of certain parts of the stack, especially on the server side where these things might actually matter. The only question is whether we acknowledge this reality in the architecture and API and create a bin for them, or ignore this reality and have every implementation hack their specific protocol properties in anyway.

**Comment by britram** [comment]
> About §9, this whole current structure is currently messy

agreed, and I think your proposed remedy (to split protocol properties out of pre-establishment, possibly up into §9) and to refer forward to them from there is the right way to go. My queue of pending edits is pretty deep so I might leave this one for you (@mwelzl) to do though.

**Comment by mwelzl** [comment]
1) About @tfpauly 's paragraph, I see that point and ok, I'm convinced - we don't want to end up with "clean but lame".  But we should at least not say "must be possible to specify". About the examples, I think we should not have the ACK stretching thing because it's not related to standards. Finding examples is hard - because if I think it's something an application should care about, I would have written it as such in minset and we'd be discussing it in a different context here already  :-) Maybe we really shouldn't have any examples. Let me propose an update for this text:

***
In order to specify Specific Protocol Properties, Transport System implementations MAY offer applications to attach a set of options to the Preconnection object, associated with a specific protocol. For example, an application could specify a set of TCP Options to use if and only if TCP is selected by the system. Such properties MUST NOT be assumed to apply across different protocols.
***

2) @britram - about "Capacity Profile as a Transport Preference", okay, but how do you then change the DSCP on a Connection?

3) @britram - regarding the messy structure related to §9 and the bit you want to leave to me: ACK !  But I'm keeping my hands off right now, of course. Maybe I can do this tonight, when you're done with your pass?!

**Comment by britram** [comment]
> regarding the messy structure related to §9 and the bit you want to leave to me...

I think I fixed §9, no worries. 

> about "Capacity Profile as a Transport Preference", okay, but how do you then change the DSCP on a Connection?

That is a very good question...

So one of the keys to fixing the messy structure of §9 is the observation that the set of Protocol Properties we enumerate in the current §5.2.2 can't really productively be used in protocol or path selection -- basically, allowing you to specify these in preconnection allows you to tweak them before turning up any candidates. Capacity Profile is weird, in that it is potentially useful in protocol and path selection as well as in scheduling afterward. I'm not sure how to do later DSCP manipulation, other than via Send Properties.

**Comment by britram** [comment]
...following up, Capacity Profile is also a send property (as Timeliness); we can simply leave it there and refer back to the transport parameter.

**Comment by mwelzl** [comment]
I don't know, this is all getting too confusing. The text that I currently see there just lists these things as if they could be *used* during the pre-establishment phase; clearly, this is not what it's about in this phase. It's about stating that you will want to have access to this kind of functionality later. I phrased it this way in minset.

There's also a comment in there now that asks "Should checksum coverage be considered to apply generally? This only seems useful for UDP, etc" - sigh... isn't this the whole point, to offer things that may only be useful with protocol X but don't cause a problem when running e.g. over TCP ? ... I mean, following that argument, we don't need to consider messages, or lifetime, or a ton of other things.

My answer to this is OF COURSE and HOW OFTEN DO I HAVE TO SAY IT and WHY DOES MINSET EXIST   :-)
