### ISSUE TITLE
Path selection properties (may be similar to Anna's comment)

### ISSUE THREAD

**Issue by gorryfair** [taps-api/drafts#78]
I am not sure why the path selection properties are constrained in this way. The NEAT architecture allows non-local path information to be also used - such as the learned PMTU, or information learned through a PvD mechanism. I think this is important to include and that we should not constrain the system to local functions. But maybe I am misreading this? - since "throughput" and "latency" surely are discovered characteristics?
- I think I would be happier to explicitly give examples of characteristics that are configured locally, or are learned about a path.

**Comment by tfpauly** [comment]
Yes, this should include both locally known and discovered properties.

**Comment by tfpauly** [comment]
I agree that path selection is based on both locally known and discovered properties, so this should be clear about that. However, since this is describing application-set constraints and preferences, the application may not be able to rely on the discovery of the remote properties getting results. I'll rework the text a bit.

**Comment by gorryfair** [comment]
I'm sure reworking will fix :-)

**Comment by tfpauly** [comment]
Fixed in text with PMTU example.
