### ISSUE TITLE
Submit -00 of Architecture Draft

### ISSUE THREAD

**Issue by tfpauly** [taps-api/drafts#91]
We're planning on submitting the architecture draft first (if there are no major objections) to get it available for people to start looking at, and because it's the most ready at this point.

I'm planning on submitting by end-of-day Monday 2/26. If anyone has any nits or last changes, please let me know. We can, of course, update if we need further reconciliation with the other drafts before the submission deadline!

**Comment by mwelzl** [comment]
I gave this a careful read now and I like it a lot!

I have fixed some (truly tiny) nits; there are three bigger things that I didn't touch:

1) it's strange that the abstract appears again as the first paragraph of the intro. I think this can safely be removed.

2) I think you wanted to avoid the use of "TAPS", but (only!) in the security considerations section, it's all over the place. I didn't want to mess with this text, but I think this would be good to update too.

3) I think it's not really correct to represent Connection Groups as an implementation concept only, as we do expose such groups too. However, not everything that the API does must be described in this architecture document, and I wouldn't know how / where to put it without making things uglier than they need to be.  I just wanted to note this issue here, but I think it's safe to ignore (at least for -00).

**Comment by tfpauly** [comment]
@mwelzl Thanks! Addressed nits 1 & 2; we can move 3 around in the future, as you say.

**Comment by abrunstrom** [comment]
I now also made it to the end of my read through (too many interruptions) . I also like it! 
Filed a separate issue for the last inconsistency I detected around the term Policy System.

**Comment by tfpauly** [comment]
Thanks, @abrunstrom. Addressed your issue!

**Comment by abrunstrom** [comment]
@tfpauly Thanks, looks good!

**Comment by britram** [comment]
ship it.

**Comment by tfpauly** [comment]
See: https://datatracker.ietf.org/doc/draft-pauly-taps-arch/
