### ISSUE TITLE
Work out the relationship between Connection Groups and Preconnection

### ISSUE THREAD

**Issue by britram** [taps-api/drafts#95]
We create Connection Groups via `Clone().`

It would be nice to be able to create groups during pre-establishment.

But you need a Connection to `Clone()` a connection.

There are a few possible syntaxes to use here, we should pick one. For now, will drop mention of being able to clone in pre-establishment.

**Comment by britram** [comment]
yeah that's probably simplest. need to think a bit about how the dynamics of that would work (is Clone() just Initiate() with the implication you'll clone the initiated thing? is Clone() of a Preconnection that's already been consumed just a Clone() on the resulting Connection?_

**Comment by mwelzl** [comment]
Hm, can we say that cloning a preconnection doesn't do anything but create a new preconnection instance, and in line with the "entanglement" that we have for groups in general, if one of them gets connected, this also turns all its clones from preconnections into connections?

**Comment by csperkins** [comment]
Having `Clone()` on a `Preconnection` generate another `Preconnection` that's entangled with the original makes sense. I'm not sure calling `Initiated()` on one of the cloned `Preconnection` objects should force the others to connect though – I'd rather expect it to mean that when the others are initiated, they instantiate as a sub-flow on the existing connection group. 

That is, I think it makes sense to be able to instantiate a connection while retaining a reference to a `Preconnection` that _could_ become a sub-flow within that connection, but doesn't have to do so.

**Comment by mwelzl** [comment]
> I'm not sure calling Initiated() on one of the cloned Preconnection objects should force the others to connect though – I'd rather expect it to mean that when the others are initiated, they instantiate as a sub-flow on the existing connection group.

Whether a connection is a sub-flow or not should be hidden to the application; ideally, it should be a sub-flow (you mean stream, I guess?) when possible, but otherwise, what would be bad about automatically initiating for clones too just for consistency?  As an app programmer, if you don't want this, don't clone...

**Comment by csperkins** [comment]
If you clone, then when you initiate the clone you get a stream rather than a new connection, I agree. But, I don't see we can force the clone to connect just because the master stream does. 

Partly this is an API thing. If I `clone()` a `Preconnection` and get a new `Preconnection` object, I don't see how the API can force the new `Preconnection` to automatically change type to `Connection`. But, partly, it also matches protocol semantics: I have something that _could_ become a stream, but that doesn't mean I want to be become a stream _now_ just because I initiated the underlying connection.

**Comment by mwelzl** [comment]
About this:
> But, I don't see we can force the clone to connect just because the master stream does.
> Partly this is an API thing. If I clone() a Preconnection and get a new Preconnection object, I don't see how the API can force the new Preconnection to automatically change type to Connection. 

I don't understand why this can't or shouldn't be done - but maybe this is something about the underlying p2p semantics that I miss.

About this:
> I have something that could become a stream, but that doesn't mean I want to be become a stream now just because I initiated the underlying connection.

I wonder, what's the problem with this being a stream right away?  What's the disadvantage of immediately connecting?

I can only think of "you may want this to have different properties than the original Preconnection object", but in this case, you just don't want to use Clone().

I'm probably missing something and I don't have a strong opinion about this, though.

**Comment by csperkins** [comment]
It's nothing about underlying p2p semantics, but more how to programming API works. If I write code that looks something like:
``` Rust
let a = Preconnection::new();  // a is a Preconnection
let b = a.clone();             // b is a Preconnection, entangled with a
let c = a.Initiate();          // c is a Connection; a is consumed and goes out of scope
```
then the type of `b` shouldn't change just because I called a method on `a`.

Secondly, the disadvantage of immediately connecting is that I use resources on the connection. It allocates a stream identifier, for example. I may not want to do that just yet, because I don't know for sure if this stream will be needed, and there might be a finite number of streams that can be created.

**Comment by mwelzl** [comment]
Ah, I see, you're thinking real object orientation here. In C this wouldn't matter. Either way there's some awkwardness to "entanglement" (hence the choice of an awkward word for it): if you change parameters on one of the "connections", it affects others too (because they may really only be streams of a single association).

Let's assume that they don't auto-initiate: couldn't this cause inconsistencies?  I connect a, but not yet b; I change properties of b => normally, these would automatically change for a too...  but now a is connected, yet b is not...  maybe that's okay, but I have a feeling that this is asking for trouble.

**Comment by csperkins** [comment]
I'd assume that there would be limits on what properties of a clone you can change once the original has been connected. Returning an error ("can't change property X on clone of connection") seems, to me, a less surprising operation than having cloned preconnections auto-connect.

**Comment by britram** [comment]
all this sounds eminently reasonable to me, and can easily be done for -00. moving to london (not yet assigning to self though, working on #93 and #101...

**Comment by britram** [comment]
making progress today (yay!) so this one's mine...

**Comment by mwelzl** [comment]
thanks!!

**Comment by britram** [comment]
working on this, I note another problem: we now have positive linear Priorities over connection groups, and inverse discrete Niceness over individual messages. This is gratuitously inconsistent. I'm writing this up as Niceness for now. Speak up if you really, really hate this.

**Comment by mwelzl** [comment]
I speak up just to say I don't care. To me the Niceness stuff isn't nearly as intuitive as priorities, but this is just a matter of taste and doesn't matter. Syntactical sugar: if I'll ever write an implementation against this interface I'll add a shim that inverts the numbers  :-)

**Comment by csperkins** [comment]
Agree with @mwelzl – it doesn't matter which we pick, but we should be consistent.
